[package]
name = "gnuplot-demo"
version = "0.1.0"
authors = ["guni1192 <ad2314ce71926@gmail.com>"]
edition = "2018"

[dependencies]
gnuplot = "0.0.29"
clap = "2.32"
serde = "*"
serde_derive = "*"
csv = "1"
